AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  environment:
    Description: Environment to use.
    Type: String

  artifactsBucket:
    Type: String

Resources:
  ## TABLES ##
  TablesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./nested-stacks/template-dynamo.yaml
      Parameters:
        environment: !Ref environment

  ## ROLES ##
  RolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./nested-stacks/template-roles.yaml
      Parameters:
        environment: !Ref environment
        usersTableName: !GetAtt [TablesStack, Outputs.usersTableName]
        reservationsTableName:
          !GetAtt [TablesStack, Outputs.reservationsTableName]
        carsTableName: !GetAtt [TablesStack, Outputs.carsTableName]

  # ## LAMBDA FUNCTIONS ##
  LambdaHandlerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./nested-stacks/template-lambda.yaml
      Parameters:
        environment: !Ref environment
        usersTableName: !GetAtt [TablesStack, Outputs.usersTableName]
        writeUsersLambdaRoleArn:
          !GetAtt [RolesStack, Outputs.WriteUsersLambdaRoleArn]
        readUsersLambdaRoleArn:
          !GetAtt [RolesStack, Outputs.ReadUsersLambdaRoleArn]
        reservationsTableName:
          !GetAtt [TablesStack, Outputs.reservationsTableName]
        writeReservationLambdaRoleArn:
          !GetAtt [RolesStack, Outputs.WriteReservationsLambdaRoleArn]
        readReservationLambdaRoleArn:
          !GetAtt [RolesStack, Outputs.ReadReservationsLambdaRoleArn]
        carsTableName: !GetAtt [TablesStack, Outputs.carsTableName]
        writeCarLambdaRoleArn:
          !GetAtt [RolesStack, Outputs.WriteCarsLambdaRoleArn]
        readCarLambdaRoleArn:
          !GetAtt [RolesStack, Outputs.ReadCarsLambdaRoleArn]

  # ## API GATEWAY AND RELATED RESOURCES ##
  APIStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdaHandlerStack
    Properties:
      TemplateURL: ./nested-stacks/template-apigateway.yaml
      Parameters:
        environment: !Ref environment
        artifactsBucket: !Ref artifactsBucket
        readUserLambdaArn:
          !GetAtt [LambdaHandlerStack, Outputs.ReadUserLambdaArn]
        createUserLambdaArn:
          !GetAtt [LambdaHandlerStack, Outputs.CreateUserLambdaArn]
        updateUserLambdaArn:
          !GetAtt [LambdaHandlerStack, Outputs.UpdateUserLambdaArn]
        deleteUserLambdaArn:
          !GetAtt [LambdaHandlerStack, Outputs.DeleteUserLambdaArn]
        readReservationLambdaArn:
          !GetAtt [LambdaHandlerStack, Outputs.ReadReservationLambdaArn]
        readAllCarReservationsArn:
          !GetAtt [LambdaHandlerStack, Outputs.ReadAllCarReservationsArn]
        createReservationLambdaArn:
          !GetAtt [LambdaHandlerStack, Outputs.CreateReservationLambdaArn]
        updateReservationLambdaArn:
          !GetAtt [LambdaHandlerStack, Outputs.UpdateReservationLambdaArn]
        deleteReservationLambdaArn:
          !GetAtt [LambdaHandlerStack, Outputs.DeleteReservationLambdaArn]
        readCarLambdaArn: !GetAtt [LambdaHandlerStack, Outputs.ReadCarLambdaArn]
        readCarsLambdaArn:
          !GetAtt [LambdaHandlerStack, Outputs.ReadCarsLambdaArn]
        createCarLambdaArn:
          !GetAtt [LambdaHandlerStack, Outputs.CreateCarLambdaArn]
        updateCarLambdaArn:
          !GetAtt [LambdaHandlerStack, Outputs.UpdateCarLambdaArn]
        deleteCarLambdaArn:
          !GetAtt [LambdaHandlerStack, Outputs.DeleteCarLambdaArn]
